In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Lending-company.csv', index_col='StringID')

In [3]:
Lending_co_data= data.copy()
Lending_co_data

LoanID    Product CustomerGender     Location    Region  \
StringID                                                               
LoanID_1          1  Product B         Female   Location 3  Region 2   
LoanID_2          2  Product D         Female   Location 6  Region 6   
LoanID_3          3  Product B           Male   Location 8  Region 3   
LoanID_4          4  Product A           Male  Location 26  Region 2   
LoanID_5          5  Product B         Female  Location 34  Region 3   
...             ...        ...            ...          ...       ...   
LoanID_1039    1039  Product B           Male  Location 73  Region 6   
LoanID_1040    1040  Product A           Male  Location 82  Region 1   
LoanID_1041    1041  Product A   NotSpecified  Location 11  Region 4   
LoanID_1042    1042  Product B         Female  Location 26  Region 6   
LoanID_1043    1043  Product A   NotSpecified  Location 94  Region 6   

             TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  \
StringID                                                               
LoanID_1        17600.0  04/07/2018     2200         45          365   
LoanID_2            NaN  02/01/2019     2200         45          365   
LoanID_3        16600.0  08/12/2016     1000         45          365   
LoanID_4        17600.0         NaN     2200         45          365   
LoanID_5        21250.0  28/10/2017     2200         55          365   
...                 ...         ...      ...        ...          ...   
LoanID_1039     17300.0  29/12/2018     2200         45          365   
LoanID_1040         NaN  28/03/2018     2200         45          365   
LoanID_1041     17300.0  26/04/2018     2200         45          365   
LoanID_1042     16300.0  25/10/2016     1000         45          365   
LoanID_1043     17300.0  15/05/2019     2200         45          365   

             AmtPaid36  AmtPaid60  AmtPaid360        LoanStatus  
StringID                                                         
LoanID_1          3221       4166       14621            Active  
LoanID_2          3161       4096       16041            Active  
LoanID_3          2260       3205       16340               NaN  
LoanID_4          3141       4166       16321            Active  
LoanID_5          3570       4745       14720            Active  
...                ...        ...         ...               ...  
LoanID_1039       3251       4743       16617  Finished Payment  
LoanID_1040       4090       5582       16617  Finished Payment  
LoanID_1041       4051       5143       16617  Finished Payment  
LoanID_1042       1930       3462       15617  Finished Payment  
LoanID_1043       4451       4743       16617  Finished Payment  

[1043 rows x 14 columns]

In [5]:
Lending_co_data.loc['LoanID_3', 'Region']

'Region 3'

In [7]:
Lending_co_data.loc[['LoanID_1', 'LoanID_3'],:]

LoanID    Product CustomerGender    Location    Region  TotalPrice  \
StringID                                                                       
LoanID_1       1  Product B         Female  Location 3  Region 2     17600.0   
LoanID_3       3  Product B           Male  Location 8  Region 3     16600.0   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_3  08/12/2016     1000         45          365       2260       3205   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_3       16340        NaN

In [15]:
#lets create an nd array and perform operation running over an axis
# axis=0 means run through each coloumn
# axis=1 means run through each row

import numpy as np
matrix_a = np.array([[1,2,3],[4,5,6]], dtype =np.float32)

In [16]:
mean_reuslt= np.mean(matrix_a, axis=0)

In [17]:
mean_reuslt

array([2.5, 3.5, 4.5], dtype=float32)

In [18]:
mean_result_row= np.mean(matrix_a, axis =1)

In [19]:
mean_result_row

array([2., 5.], dtype=float32)

In [22]:
len(martix_a)

2

In [23]:
martix_a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
martix_a[:,1:]

array([[2, 3],
       [5, 6]])

In [28]:
array_empty= np.empty(shape=(2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.empty_like(martix_a)

array([[         0, 1074003968,          0],
       [1074528256,          0, 1074921472]])

In [31]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [32]:
array_gen= gen(pcg())


In [33]:
array_gen.normal(size= (5,5))

array([[-0.57986909,  0.92642016,  0.12901853,  0.54422642,  0.28246674],
       [ 1.35277466,  0.58691167,  0.31048622,  0.59714175,  1.01114399],
       [ 0.06819541, -1.40296766,  0.40410277,  1.72421645,  1.37965006],
       [ 0.63346063, -0.5204606 , -1.25499528,  0.58129726, -1.76956543],
       [-1.44155832,  0.82404544,  1.29828394,  0.45061114,  0.15735233]])

In [35]:
array_RG= gen(pcg(seed =365))
array_RG.normal(size= (4,4))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641],
       [-0.6866818 , -0.50922173, -0.7999526 ,  0.73041825],
       [ 0.08825439, -2.1177576 ,  0.65526774, -0.48095012],
       [-0.5519114 , -0.58578662, -0.98257896,  1.12378166]])

In [37]:
array_RG= gen(pcg(seed =365))
array_RG.poisson(lam= 10 ,size= (4,4))


array([[11, 12, 12, 14],
       [13,  9, 10, 11],
       [11,  8, 11,  8],
       [10,  9, 14,  7]], dtype=int64)